name: Build & deploy

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build project
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Deploy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.S3_ID }}
          aws_secret_access_key: ${{ secrets.S3_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'build'
          destination_dir: 'release'
